import { SubmittedUser } from './SubmittedUser';

export interface EventDashboardFormProps {
    _id: string;
    name: string;
    category: string;
    subcategory?: string;
    tags?: string[];
    mode: string;
    type: string;
    address?: string;
    webLink?: string;
    date: string;
    startTime: string;
    endTime: string;
    timeZone: string;
    showTime: boolean;
    showDate: boolean;
    confirmed?: boolean;
    description: string;
    web?: string;
    organizedBy?: string[];
    contactEmail?: string;
    isPrivate: boolean;
    language: string[];
    image?: string;
    video?: string;
    capacity: number;
    capacityOnline: number;
    qrEvent?: string;
    qrAttendees?: string[];
    attendees?: string[];
    submitted: SubmittedUser[];
    submittedOnline: string[];
    price?: number;
    payment?: string;
    visibility?: boolean;
    isLimited: boolean;
    isLimitedOnline: boolean;
    subcategoryLogo: string;
    active?: boolean;
}